app:
  name: "web_app"
  mode: "dev"
  port: 8081
  start_time: "2022-05-03"
  machine_id: 1

auth:
  jwt_expire: 8760

log:
  level: "debug"
  filename: "web_app.log"
  max_size: 200
  max_age: 30
  max_backup: 7

database:
  hostname:  127.0.0.1
  dbtype: mysql
  port: 3306
  username: root
  password:  123456
  base: "bluebell"
  ping_attempts: 3



